sudo: false
language: node_js
cache:
  yarn: true 
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - lts/*
before_install:
  - chmod +x .travis/before_install.sh
after_success: 
  - .travis/after_success.sh
git:
  depth: 1
