sudo: false
language: node_js
node_js:
  - '10'
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - lts/*
before_install:
  - chmod +x .travis/before_install.sh
after_success:
  - .travis/after_success.sh
  - test $TRAVIS_BRANCH = "master" && yarn semantic-release
script: yarn lint
git:
  depth: 1
